#group: deprecated

language: c

compiler:
  - gcc
  - clang

matrix:
  exclude:
      - compiler: gcc
      - compiler: clang
  include:
       - sudo: required
         compiler: gcc
       - sudo: required
         compiler: gcc
         dist: trusty
       # We disable 12.04 because we have a header issue here w/ clang
       #- sudo: required
       #  compiler: clang
       - sudo: required
         compiler: clang
         dist: trusty

before_install:
  - travis_retry sudo add-apt-repository -y ppa:adiscon/v8-stable
  - travis_retry sudo apt-get install -y clang
  - travis_retry sudo pip install -U sphinx
  - travis_retry sudo apt-get update

install:
  - travis_retry sudo apt-get install -y libpcre3-dev libpcre3-dbg valgrind python-pip
  - travis_retry sudo apt-get install -y libestr libestr-dev libfastjson-dev
# the following is a work-around to solve the
# "too old autoconf-archive" problem
  - mkdir tmp
  - cd tmp
  - git clone git://git.sv.gnu.org/autoconf-archive.git
  - sudo cp autoconf-archive/m4/* /usr/share/aclocal
  - cd ..
  - rm -rf tmp

script:
  - CI/check_codestyle.sh
  - autoreconf --force --verbose --install
# note: we enable regexp to check the v1 compatibility layer. v2 does
# not have it, nor is it recommended to enable it.
  - if [ "$CC" == "gcc" ] ; then ./configure --prefix=/opt/liblognorm --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --libdir=/usr/lib64 --enable-debug --enable-testbench --enable-docs --enable-regexp --enable-valgrind; fi
  - if [ "$CC" == "gcc" ] ; then make && make dist && make check && sudo make install; fi
  # here come the clang test. So far, we just call the static analyzer
  - if [ "$CC" == "clang" ] ; then export CFLAGS="-Werror -Wfatal-errors -std=c99" ; fi
  - if [ "$CC" == "clang" ] ; then scan-build ./configure --prefix=/opt/liblognorm --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --libdir=/usr/lib64 --enable-debug --enable-testbench --enable-regexp ; fi
  - if [ "$CC" == "clang" ] ; then scan-build --status-bugs make ; fi
